version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - 27017:27017

